let suggestions = [
    "AksharDham,Gandhinagar",
    "Ajanta caves,Maharastra",
    "Goa",
    "Div",
    "Daman",
    "Gir Somnath,Gujarat",
    "Gir Forest,Gujarat",
    "Taj Mahal,Agra,UP",
    "Mahabaleshwar,Maharastra",
    "Matheran,Maharastra",
    "Saputara,Gujarat",
    "Shimla,Himachal Pradesh",
    "Manali,Himachal Pradesh",
    "Kedarnath,UttaraKhand",
    "Badrinath,UttaraKhand",
    "Nainital,UttaraKhand",
    "Srinagar,Jammu & Kashmir",
    "Mount Abu,Rajasthan",
    "Ujjain,Madhya Pradesh",
    "Udaipur,Rajasthan",
    "Shirdi,Maharastra",
];